# Schema for the configuration files of the Tidy Feedback module.

tidy_feedback.settings:
  type: config_object
  label: "Tidy Feedback settings"
  mapping:
    banner_position:
      type: string
      label: "Banner position"
    highlight_color:
      type: string
      label: "Highlight color"
    enable_screenshots:
      type: boolean
      label: "Enable screenshots"
    notify_email:
      type: email
      label: "Notification email"
