#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$script_dir"

execute() {
  composer require --dev symfony/phpunit-bridge
  shell vendor/bin/phpstan --configuration="$module_path/phpstan.neon" --memory-limit=256M
}

source "$script_dir/base"
